version: "3.8"

networks:
  multicast_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"  # Permite comunicação entre contêineres
      com.docker.network.bridge.enable_ip_masquerade: "true"  # Permite o tráfego de saída para a rede externa

services:
  wot-server:
    build: .
    volumes:
      - .:/app  # Volume para permitir a alteração do código sem precisar reconstruir a imagem
    ports:
      - "8080:8080"  # Expondo a porta do contêiner para a rede externa
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      multicast_network:  # Usando a rede personalizada
        aliases:
          - datastore.local  # Alias que será resolvido por mDNS na rede Docker
    restart: unless-stopped
    extra_hosts:
      - "wot-assistant.local:127.0.0.1"  # Adicionando o alias para mDNS
